dist: xenial

language: go

sudo: true

services:
  - docker

go:
  - 1.13.x

install: true

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
  - make amq-start
  - make amq-logs &

script:
  - make lint
  - make unit-test
  - make integration-test

after_script:
  - make amq-stop
