// Code generated by protoc-gen-go. DO NOT EDIT.
// source: acquia/messages/hosting/Application.proto

package hosting

import (
	fmt "fmt"
	shared "github.com/acquia/message-broker-sdk-go/pkg/acquia/messages/shared"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateApplication struct {
	Header               *shared.Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	AccountUUID          string         `protobuf:"bytes,2,opt,name=accountUUID,proto3" json:"accountUUID,omitempty"`
	ApplicationUUID      string         `protobuf:"bytes,3,opt,name=applicationUUID,proto3" json:"applicationUUID,omitempty"`
	ApplicationName      string         `protobuf:"bytes,4,opt,name=applicationName,proto3" json:"applicationName,omitempty"`
	ApplicationLabel     string         `protobuf:"bytes,5,opt,name=applicationLabel,proto3" json:"applicationLabel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateApplication) Reset()         { *m = CreateApplication{} }
func (m *CreateApplication) String() string { return proto.CompactTextString(m) }
func (*CreateApplication) ProtoMessage()    {}
func (*CreateApplication) Descriptor() ([]byte, []int) {
	return fileDescriptor_1883202f64b28a01, []int{0}
}

func (m *CreateApplication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateApplication.Unmarshal(m, b)
}
func (m *CreateApplication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateApplication.Marshal(b, m, deterministic)
}
func (m *CreateApplication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateApplication.Merge(m, src)
}
func (m *CreateApplication) XXX_Size() int {
	return xxx_messageInfo_CreateApplication.Size(m)
}
func (m *CreateApplication) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateApplication.DiscardUnknown(m)
}

var xxx_messageInfo_CreateApplication proto.InternalMessageInfo

func (m *CreateApplication) GetHeader() *shared.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CreateApplication) GetAccountUUID() string {
	if m != nil {
		return m.AccountUUID
	}
	return ""
}

func (m *CreateApplication) GetApplicationUUID() string {
	if m != nil {
		return m.ApplicationUUID
	}
	return ""
}

func (m *CreateApplication) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *CreateApplication) GetApplicationLabel() string {
	if m != nil {
		return m.ApplicationLabel
	}
	return ""
}

type ApplicationCreated struct {
	Header               *shared.Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ApplicationUUID      string         `protobuf:"bytes,2,opt,name=applicationUUID,proto3" json:"applicationUUID,omitempty"`
	Status               string         `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ApplicationCreated) Reset()         { *m = ApplicationCreated{} }
func (m *ApplicationCreated) String() string { return proto.CompactTextString(m) }
func (*ApplicationCreated) ProtoMessage()    {}
func (*ApplicationCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_1883202f64b28a01, []int{1}
}

func (m *ApplicationCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationCreated.Unmarshal(m, b)
}
func (m *ApplicationCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationCreated.Marshal(b, m, deterministic)
}
func (m *ApplicationCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationCreated.Merge(m, src)
}
func (m *ApplicationCreated) XXX_Size() int {
	return xxx_messageInfo_ApplicationCreated.Size(m)
}
func (m *ApplicationCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationCreated.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationCreated proto.InternalMessageInfo

func (m *ApplicationCreated) GetHeader() *shared.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ApplicationCreated) GetApplicationUUID() string {
	if m != nil {
		return m.ApplicationUUID
	}
	return ""
}

func (m *ApplicationCreated) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateApplication)(nil), "acquia.messages.hosting.CreateApplication")
	proto.RegisterType((*ApplicationCreated)(nil), "acquia.messages.hosting.ApplicationCreated")
}

func init() {
	proto.RegisterFile("acquia/messages/hosting/Application.proto", fileDescriptor_1883202f64b28a01)
}

var fileDescriptor_1883202f64b28a01 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xe9, 0xaa, 0x0b, 0x66, 0x0f, 0x6a, 0x0e, 0x5a, 0x3c, 0x48, 0x59, 0x2f, 0x55, 0x68,
	0x02, 0x0a, 0xde, 0x75, 0x15, 0x14, 0xc4, 0xc3, 0xc2, 0x5e, 0xbc, 0x4d, 0xd3, 0x21, 0x0d, 0xdd,
	0x36, 0x35, 0x49, 0x5f, 0xc3, 0x37, 0xf5, 0x1d, 0xc4, 0x34, 0x62, 0xed, 0xae, 0x17, 0x4f, 0x21,
	0x3f, 0x5f, 0xfe, 0xe1, 0x63, 0x42, 0x2e, 0x40, 0xbc, 0x75, 0x0a, 0x78, 0x8d, 0xd6, 0x82, 0x44,
	0xcb, 0x4b, 0x6d, 0x9d, 0x6a, 0x24, 0xbf, 0x6d, 0xdb, 0xb5, 0x12, 0xe0, 0x94, 0x6e, 0x58, 0x6b,
	0xb4, 0xd3, 0xf4, 0xa4, 0x47, 0xd9, 0x37, 0xca, 0x02, 0x7a, 0x7a, 0x3e, 0xee, 0xb0, 0x25, 0x18,
	0x2c, 0xc2, 0xd1, 0xbf, 0x9e, 0x7f, 0x44, 0xe4, 0x68, 0x61, 0x10, 0x1c, 0x0e, 0x9a, 0xe9, 0x0d,
	0x99, 0x96, 0x08, 0x05, 0x9a, 0x38, 0x4a, 0xa2, 0x74, 0x76, 0x75, 0xc6, 0xc6, 0x43, 0x42, 0xc9,
	0xa3, 0xa7, 0x96, 0x81, 0xa6, 0x09, 0x99, 0x81, 0x10, 0xba, 0x6b, 0xdc, 0x6a, 0xf5, 0x74, 0x1f,
	0x4f, 0x92, 0x28, 0xdd, 0x5f, 0x0e, 0x23, 0x9a, 0x92, 0x03, 0xf8, 0x19, 0xe4, 0xa9, 0x1d, 0x4f,
	0x8d, 0xe3, 0x11, 0xf9, 0x02, 0x35, 0xc6, 0xbb, 0x1b, 0xe4, 0x57, 0x4c, 0x2f, 0xc9, 0xe1, 0x20,
	0x7a, 0x86, 0x1c, 0xd7, 0xf1, 0x9e, 0x47, 0x37, 0xf2, 0xf9, 0x7b, 0x44, 0xe8, 0xc0, 0xb4, 0x57,
	0x2f, 0xfe, 0x2d, 0xbc, 0x45, 0x67, 0xb2, 0x5d, 0xe7, 0x98, 0x4c, 0xad, 0x03, 0xd7, 0xd9, 0xe0,
	0x1b, 0x6e, 0x77, 0x0f, 0xaf, 0x0b, 0xa9, 0x5c, 0xd9, 0xe5, 0x4c, 0xe8, 0x9a, 0xff, 0x5e, 0x59,
	0x96, 0x1b, 0x5d, 0xa1, 0xc9, 0x6c, 0x51, 0x65, 0x52, 0xf3, 0xb6, 0x92, 0xfc, 0x8f, 0x7f, 0x91,
	0x4f, 0xfd, 0x3a, 0xaf, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x03, 0x9b, 0xb1, 0xa6, 0x39, 0x02,
	0x00, 0x00,
}
